###
POST http://localhost:3100/api/v1/workers/new-worker HTTP/1.1
Content-Type: application/json

{
    "firstname": "test1",
    "lastname": "test1",
    "work":[
        {
            "id_work":"1",
            "name_work":"Database"
        }
    ],
    "type_document": "CC",
    "document_number": "1"
} 

###
GET http://localhost:3100/api/v1/workers/ HTTP/1.1
###
GET http://localhost:3100/api/v1/workers/6511ef215d8421dd3328f042 HTTP/1.1
###
DELETE  http://localhost:3100/api/v1/workers/651b2489246f5861752538e9 HTTP/1.1
###
PATCH  http://localhost:3100/api/v1/workers/651b24ec246f5861752538f6 HTTP/1.1
Content-Type: application/json

{
    "firstname":"test1",
    "lastname":"test1",
    "work":[
        {
            "id_work":"1",
            "name_work":"database oracle"
        }
    ],
    "type_document":"CC",
    "document_number":"1"
}

//client
###
POST http://localhost:3100/api/v1/workers/new-worker HTTP/1.1
Content-Type: application/json

{
    "firstname": "client1",
    "lastname": "client1",
} 

###
GET http://localhost:3100/api/v1/clients/ HTTP/1.1
###
GET http://localhost:3100/api/v1/clients/6511ef215d8421dd3328f042 HTTP/1.1
###
DELETE  http://localhost:3100/api/v1/clients/651b2489246f5861752538e9 HTTP/1.1
###
PATCH  http://localhost:3100/api/v1/clients/651b24ec246f5861752538f6 HTTP/1.1
Content-Type: application/json

{
    "firstname":"test1",
    "lastname":"test1",
    "work":[
        {
            "id_work":"1",
            "name_work":"database oracle"
        }
    ],
    "type_document":"CC",
    "document_number":"1"
}


